name: rgn-export
on: workflow_dispatch
permissions: { contents: write }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: '3.11' }
    - name: Show tree
      run: |
        pwd
        ls -la
        find . -maxdepth 2 -type f | sort
    - name: Install deps
      run: python -m pip install --upgrade pip pandas numpy
    - name: Locate CSVs
      run: |
        python - <<'PY'
        import glob, os, sys
        def pick(pats):
            for pat in pats:
                m = sorted(glob.glob(pat, recursive=True))
                if m: return m[0]
            return ''
        zones = pick(['**/TSM-136D_zonen_recommended.csv','**/*zonen*recommended*csv'])
        rest  = pick(['**/TSM-136D_R_estimates.csv','**/*R_estimates*csv'])
        base  = pick(['**/TSM-136D_zonen_baseline.csv','**/*zonen*baseline*csv'])
        print('ZONES =', zones); print('REST =', rest); print('BASELINE =', base)
        if not zones or not rest:
            print('::error::Missing required CSVs (zones/rest).')
            sys.exit(1)
        with open(os.environ['GITHUB_ENV'],'a') as f:
            f.write(f"ZONES={zones}\nREST={rest}\nBASELINE={base}\n")
        PY
    - name: Preview heads
      run: |
        echo "ZONES=$ZONES"; echo "REST=$REST"; echo "BASELINE=$BASELINE"
        head -n 3 "$ZONES" || true
        head -n 3 "$REST" || true
        head -n 3 "$BASELINE" || true
    - name: Run exporter
      run: python rgn_export_v0.2.1.py --zones "$ZONES" --rest "$REST" --baseline "$BASELINE" --outdir .
    - name: Commit outputs
      run: |
        git config user.name "rgn-bot"
        git config user.email "rgn-bot@example.com"
        git add RGN_state_v0.2.csv RGN_manifest_v0.2.json RGN_report_v0.2.md
        git diff --cached --quiet || git commit -m "RGN export v0.2 (auto)"
        git push
