name: TSM Bridge CI (smoke)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Say hello
        run: echo "YAML ok ✅"
