name: TSM Bridge CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate-bridge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ✨ Sanitizer: NBSP -> Space, Tabs -> 4 Spaces
      - name: Sanitize whitespace (compute)
        run: |
          python - <<'PY'
          p = 'bridge/tsm_bridge_compute.py'
          s = open(p, 'rb').read()
          s = s.replace(b'\xc2\xa0', b' ')   # NBSP -> normal space
          s = s.replace(b'\t', b'    ')      # Tabs -> 4 spaces
          open(p, 'wb').write(s)
          print("Sanitized:", p)
          PY

      - name: Compute (mini)
        run: python bridge/tsm_bridge_compute.py --in bridge/tsm_gr_test_minidataset.csv --out /tmp/comp.csv --eps-deg 1.0 --cap-quantile 0.99 --B-lo 0.2 --B-hi 0.8

      - name: Export (matter)
        run: python bridge/tsm_gr_exporter_v0.1.py --in /tmp/comp.csv --out-prefix /tmp/exp --mode matter --rho0 1.0 --w 0.0

      - name: Validation
        run: python bridge/tsm_bridge_validation_v0.1.py --in /tmp/comp.csv --B-lo 0.2 --B-hi 0.8 --out /tmp/report.json --compare bridge/expected_computed_minidataset.csv

      - name: Print report
        run: cat /tmp/report.json
